/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package newsletter;
import java.awt.datatransfer.StringSelection;
import java.awt.Toolkit;
import java.awt.datatransfer.Clipboard;
import javax.swing.JOptionPane;

/**
 *
 * @author Jagdish
 */
public class Newsletter extends javax.swing.JFrame {

    /**
     * Creates new form Newsletter
     */
    public Newsletter() {
        initComponents();
        getStarted.setVisible(true);
        
    }
    allFunction obj=new allFunction();
    public int noArticle;
    public int articleNum=1;
    public int noOtherArticle;
    public int otherArticleNum=1;
    public int noMeme;
    public int memeNum=1;
    int n=0;
    public String[][] links;
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        getStarted = new javax.swing.JFrame();
        jLabel8 = new javax.swing.JLabel();
        numArticle = new javax.swing.JSpinner();
        jLabel9 = new javax.swing.JLabel();
        numOtherArticle = new javax.swing.JSpinner();
        jLabel10 = new javax.swing.JLabel();
        numMemes = new javax.swing.JSpinner();
        jButton3 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        meme = new javax.swing.JFrame();
        jLabel12 = new javax.swing.JLabel();
        memeTF = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        memeAltTF = new javax.swing.JTextField();
        memeNo = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        memeNo1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        artLabel = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        linkTF = new javax.swing.JTextField();
        headTF = new javax.swing.JTextField();
        imgLinkTF = new javax.swing.JTextField();
        imgAltTF = new javax.swing.JTextField();
        descTF = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        textArea = new javax.swing.JTextArea();
        jLabel14 = new javax.swing.JLabel();
        artLabel1 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        btnType = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();

        getStarted.setAlwaysOnTop(true);
        getStarted.setLocation(new java.awt.Point(100, 100));
        getStarted.setMinimumSize(new java.awt.Dimension(517, 297));

        jLabel8.setText("Num of News Article");

        numArticle.setValue(5);

        jLabel9.setText("Num of Other News Article");

        numOtherArticle.setValue(2);

        jLabel10.setText("Num of Memes");

        numMemes.setValue(3);

        jButton3.setText("Get Started");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("MS PGothic", 1, 36)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("WnCC NewsLetter");

        javax.swing.GroupLayout getStartedLayout = new javax.swing.GroupLayout(getStarted.getContentPane());
        getStarted.getContentPane().setLayout(getStartedLayout);
        getStartedLayout.setHorizontalGroup(
            getStartedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(getStartedLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(getStartedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(getStartedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(numMemes, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(getStartedLayout.createSequentialGroup()
                        .addComponent(numOtherArticle, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(numArticle, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, getStartedLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(72, 72, 72))
        );
        getStartedLayout.setVerticalGroup(
            getStartedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(getStartedLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(getStartedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(numArticle, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(getStartedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(numOtherArticle, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(getStartedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(numMemes, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(67, Short.MAX_VALUE))
        );

        meme.setAlwaysOnTop(true);
        meme.setLocation(new java.awt.Point(100, 100));
        meme.setMinimumSize(new java.awt.Dimension(488, 330));

        jLabel12.setText("Meme Image Link");

        jLabel13.setText("Meme Image Alt");

        memeNo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        memeNo.setText("Meme No : ");

        jLabel15.setFont(new java.awt.Font("MS PGothic", 1, 36)); // NOI18N
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("WnCC NewsLetter");

        jButton4.setText("Submit");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("Submit and Append");
        jButton5.setEnabled(false);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        memeNo1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout memeLayout = new javax.swing.GroupLayout(meme.getContentPane());
        meme.getContentPane().setLayout(memeLayout);
        memeLayout.setHorizontalGroup(
            memeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(memeLayout.createSequentialGroup()
                .addGroup(memeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(memeLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(memeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(memeLayout.createSequentialGroup()
                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(memeTF, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(memeLayout.createSequentialGroup()
                                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(memeAltTF))))
                    .addGroup(memeLayout.createSequentialGroup()
                        .addGap(167, 167, 167)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(memeLayout.createSequentialGroup()
                        .addGap(126, 126, 126)
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(35, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, memeLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(memeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(memeLayout.createSequentialGroup()
                        .addComponent(memeNo, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(memeNo1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(66, 66, 66))
        );
        memeLayout.setVerticalGroup(
            memeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(memeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel15)
                .addGap(13, 13, 13)
                .addGroup(memeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(memeNo1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(memeNo, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(memeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(memeTF, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(memeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(memeAltTF, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE)
                .addContainerGap())
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 204, 204));
        setMinimumSize(new java.awt.Dimension(790, 590));
        setPreferredSize(new java.awt.Dimension(790, 590));
        getContentPane().setLayout(null);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("WnCC NewsLetter");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(46, 11, 585, 43);

        artLabel.setText("Article No");
        getContentPane().add(artLabel);
        artLabel.setBounds(46, 65, 125, 37);

        jLabel3.setText("News Headline");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(40, 150, 120, 37);

        jLabel4.setText("Image Link");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(40, 200, 120, 37);
        getContentPane().add(linkTF);
        linkTF.setBounds(150, 110, 590, 37);
        getContentPane().add(headTF);
        headTF.setBounds(150, 150, 590, 37);
        getContentPane().add(imgLinkTF);
        imgLinkTF.setBounds(150, 200, 310, 37);
        getContentPane().add(imgAltTF);
        imgAltTF.setBounds(560, 200, 180, 37);
        getContentPane().add(descTF);
        descTF.setBounds(150, 250, 590, 37);

        jLabel5.setText("Image Alt");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(470, 200, 90, 37);

        jLabel6.setText("News Link");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(40, 110, 110, 37);

        jLabel7.setText("Button Type");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(40, 300, 110, 37);

        jLabel16.setText("News Description");
        getContentPane().add(jLabel16);
        jLabel16.setBounds(40, 250, 110, 37);

        jButton1.setText("Copy to Clipboard");
        jButton1.setEnabled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(420, 340, 160, 38);

        jButton2.setText("Submit");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(60, 340, 160, 38);

        textArea.setEditable(false);
        textArea.setColumns(20);
        textArea.setRows(5);
        textArea.setEnabled(false);
        jScrollPane1.setViewportView(textArea);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(46, 419, 689, 111);

        jLabel14.setText("HTML Code for newsletter : Work in Progress...");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(99, 380, 589, 33);
        getContentPane().add(artLabel1);
        artLabel1.setBounds(201, 65, 80, 37);

        jButton6.setText("Exit");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6);
        jButton6.setBounds(610, 340, 110, 35);

        btnType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Check Out", "Read More", "Check it out" }));
        getContentPane().add(btnType);
        btnType.setBounds(150, 300, 260, 30);

        jLabel2.setBackground(new java.awt.Color(222, 233, 238));
        jLabel2.setOpaque(true);
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 790, 560);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
       noArticle=(int) numArticle.getValue();
       noOtherArticle=(int) numOtherArticle.getValue();
       noMeme=(int) numMemes.getValue();
       links= new String[noMeme][2];
       getStarted.setVisible(false);
       jButton6.setVisible(false);
       textArea.append(obj.intro());
       artLabel1.setText(articleNum+"");
    }//GEN-LAST:event_jButton3ActionPerformed
    
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if(Integer.parseInt(artLabel1.getText())<=noArticle && artLabel.getText().equals("Article No")){
        textArea.append("\n");
            textArea.append(obj.news(imgLinkTF.getText(), imgAltTF.getText(), headTF.getText(), descTF.getText(), linkTF.getText(),n,(String)btnType.getSelectedItem()));
        artLabel1.setText(++articleNum+"");
        }
        if(Integer.parseInt(artLabel1.getText())>noArticle && artLabel.getText().equals("Article No")){
            artLabel.setText("Other News Article No");
            artLabel1.setText("1");
            n++;
        }
        else if(Integer.parseInt(artLabel1.getText())<=noOtherArticle && artLabel.getText().equals("Other News Article No")){
            
            textArea.append("\n");
            textArea.append(obj.news(imgLinkTF.getText(), imgAltTF.getText(), headTF.getText(), descTF.getText(), linkTF.getText(),n,(String)btnType.getSelectedItem()));
        artLabel1.setText(++otherArticleNum+"");
        n++;
        }
        if(Integer.parseInt(artLabel1.getText())>noOtherArticle && artLabel.getText().equals("Other News Article No")){
            artLabel.setVisible(false);
            artLabel1.setVisible(false);
            jButton2.setEnabled(false);
            meme.setVisible(true);
            this.setVisible(false);
            memeNo1.setText("1");
        }
        clear();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        links[memeNum-1][0]=memeTF.getText();
        links[memeNum-1][1]=memeAltTF.getText();
        memeNo1.setText(++memeNum+"");
        if(memeNum>noMeme){
        memeNo1.setText("");
            jButton4.setEnabled(false);
            memeTF.setEditable(false);
            memeAltTF.setEditable(false);
            jButton5.setEnabled(true);
        }
        clearMeme();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        textArea.append(obj.memesIntro(links, noMeme));
        this.setVisible(true);
        meme.setVisible(false);
        textArea.setEnabled(true);
        jButton1.setEnabled(true);
        jButton6.setVisible(true);
        disable_elmements();
        jLabel14.setText("HTML Code for Newsletter Completed!! Copy and paste the code in HTML File.");
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String myString = textArea.getText(); 
        StringSelection stringSelection = new StringSelection(myString); 
        Clipboard clipboard = Toolkit.getDefaultToolkit().getSystemClipboard(); 
        clipboard.setContents(stringSelection, null); 
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
     jButton1.doClick();
        JOptionPane.showMessageDialog(this,"Are you sure you want to exit?. Your code is copied to clipboard");
        System.exit(0);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    void clear(){
        descTF.setText("");
        headTF.setText("");
        imgAltTF.setText("");
        imgLinkTF.setText("");
        linkTF.setText("");
    }
    void clearMeme(){
        memeTF.setText("");
        memeAltTF.setText("");
    }
    void disable_elmements(){
        descTF.setEditable(false);
        headTF.setEditable(false);
        imgAltTF.setEditable(false);
        imgLinkTF.setEditable(false);
        linkTF.setEditable(false);
        btnType.setEnabled(false);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Newsletter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Newsletter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Newsletter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Newsletter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Newsletter().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel artLabel;
    private javax.swing.JLabel artLabel1;
    private javax.swing.JComboBox<String> btnType;
    private javax.swing.JTextField descTF;
    private javax.swing.JFrame getStarted;
    private javax.swing.JTextField headTF;
    private javax.swing.JTextField imgAltTF;
    private javax.swing.JTextField imgLinkTF;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField linkTF;
    private javax.swing.JFrame meme;
    private javax.swing.JTextField memeAltTF;
    private javax.swing.JLabel memeNo;
    private javax.swing.JLabel memeNo1;
    private javax.swing.JTextField memeTF;
    private javax.swing.JSpinner numArticle;
    private javax.swing.JSpinner numMemes;
    private javax.swing.JSpinner numOtherArticle;
    private javax.swing.JTextArea textArea;
    // End of variables declaration//GEN-END:variables
}
